version: '3.8'

services:
  softgroup:
    build:
      context: .
      args:
          UID: 1168432388
          GID: 1168400513
    ipc: host
    volumes:
      - .:/softgroup
    working_dir: /softgroup
    stdin_open: true
    tty: true
    command: bash
